version: 2.1
orbs:
  node: circleci/node@4.7.0
  docker: circleci/docker@1.4.0

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: node:lts
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - run: 
          name: Install Docker client
          command: |
            apt-get update && apt-get install -y curl
            set -x
            VER="20.10.17"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
            name: Install aws cli
            command: |
              apt-get update && apt-get install -y python3 python3-venv
              python3 -m venv venv
              . venv/bin/activate
              pip install awscli>=1.16.30
      - run:
          name: Build image
          command: |
            docker build -t $AWS_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com/$AWS_REPO:${CIRCLE_BRANCH}_${CIRCLE_SHA1:0:7} .
      - run:
          name: Push Docker image
          command: |
            # login aws
            . venv/bin/activate
            aws configure set region $AWS_REGION
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT}.dkr.ecr.${AWS_REGION}.amazonaws.com

            # push image to ecr
            docker tag $AWS_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com/$AWS_REPO:${CIRCLE_BRANCH}_${CIRCLE_SHA1:0:7} $AWS_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com/$AWS_REPO:${CIRCLE_BRANCH}
            docker push $AWS_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com/$AWS_REPO:${CIRCLE_BRANCH}_${CIRCLE_SHA1:0:7}
            #docker push $AWS_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com/$AWS_REPO:${CIRCLE_BRANCH}

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
